[[soapysdr]]
arch = "aarch64"
git-tree-sha1 = "525abc8d92706ec5e62cbada86c19040b2d15d9c"
os = "macos"

    [[soapysdr.download]]
    sha256 = "2f91fedface26185b80e432fef05a18fbbef98960c5717adc8da9ab3c6d8e78c"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.aarch64-apple-darwin.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "633f47e82bb9f6c7fb04bafe0c56949b74ee8b43"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "17d58feadc1d4e2e4cd5863dcd1c1833323a962e86bf9caea29d90ac4a3f7bdb"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.aarch64-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1638922052f8a3b0ac22612abd1cf10849c6647"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "25f292da0139902bb52a0f122bf758e4cc01970c8a5f3866363f0ded8cdd3eb7"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.aarch64-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "216feb9a154f4588b7c95dba42b28a8b3ae816a8"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "631dd9bbdc11f32e597dd787cbc15a8dc806bb24639a8e2ae23211274b76512d"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.aarch64-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fc5bf07c0dee90ad7ab19b9b7d84f8362a72495"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "105241c863fa5fdffe9269960c692f5ff18e964fa9f6b5d9f22a0e6393d575f7"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.aarch64-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09933f856734c069af636098fd7e18df29d8b25e"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "445e1c67ca6d832ea5fbe3ab6344afc864e1a87742a53c201a7dfb4814738b83"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72c16a43672e214c46583183ce2318729d42efbf"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "cec6d324e6e50ef6b581037e9b6dc461f85701031e5f1ab0b4adcee553d314a7"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94d7aa565adf675dbbb0f18161d735b746478f37"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "94942cc81caa6f54b923af4fd4c0b141a839c0a8600d0e623ffe0718c0a0f960"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d51b48c7312feed6ae9f40bc5f66894864c8fc8"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "d527b1a931d9cee371b6d1d26cd298a9651c2bd24400021f7714b766df2ad796"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c86510e665ac7be8d5ab674fb9fb983422a0049c"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "a448939f08b3b2543d30b86414d2877047b434c2305cfd47725464be505758ff"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f40b457c5988de554e68827b0b8c628e9d9c579a"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "5c3694effe58ad77e8a6aeb18b1d3f26042d330411a46ad49b76521a1a532aed"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4a01c37662ff2268bf3047832f35334a9271016"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "ac3aac5017c61768ee33317a36ba3f52d1b56d996181a0c6ec690dd6aed6d6b1"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14f999ca637b932f2b870b2e1798b8c9f8697171"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "2d5f7f38f29310736d43fd7d0503b4d0edb14fac2024acd368e04943618bf423"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88b503c97a70aecc749f178b00deb08586d6487b"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "ea71fe8b724c5e4766c4b5299c40d94b3709357b8963fd1c13b80d5031c4c698"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.i686-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfa6185072fc83ea4cc829659daafc6ae92afe54"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "dfdc2482ae414fb622a3959e0199a92979c2db2f7fd65fcc5bf3afeb767b419c"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.i686-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cae23ab18c0a39c77764d36463eed9b43aba3a38"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "813e0fda137667970be4020b68bb356ca9aa5d1cd7c96045e09ae3eebc440f1e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.i686-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be6c8365669e4973940900c3af8c6e450d57f89b"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "a46ec84465b9d6c89190dfddf3a8b978916a91c027415f5df689fb44e0293330"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.i686-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba2f9495bd30c9f0ab617f84234a7e2a598a5cda"
os = "windows"

    [[soapysdr.download]]
    sha256 = "1e1467566833dd67b2aa0c79dd30a4faf904da7b30033af90bef625c97c69a71"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.i686-w64-mingw32-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6fe2eaf32dcdc246c1145a77788d43c5fd2e0a3"
os = "windows"

    [[soapysdr.download]]
    sha256 = "99816b2b49302ee9f4a6d0aa12b1ad61037d5dfec5362498355668e65db656fb"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.i686-w64-mingw32-cxx11.tar.gz"
[[soapysdr]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "867f1ccd8f7fbd10c8b15409b95a9f6bee099a00"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "ec244e16097f049911054e212e45ec6c91badfe345bc9e932c88b2511c3b02a1"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32e75f09b16d532226ade73024826927cea8386d"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "03a1c3b38ad6c14a7e2bfcf709adbf86df2115c33930fff4e33a4c5ccb292937"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
git-tree-sha1 = "d75bc88192fa88926a827669c8a9fc6b49b0169b"
os = "macos"

    [[soapysdr.download]]
    sha256 = "0a3c073ab94bd2661c669bcefdb0e20196660f859626c8d2bade8c59c18b5b00"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-apple-darwin.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3cf624edd914220b9e1e9cbc600e64ed0e58617"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "cb7e10d6607f1cc05a5f37643e9f1c21896257a0cf5562094b3d2fcdcea6e552"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f793024cbf86c846108b84636b77b7c50f24e15"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "23ec66e574d23da393c13a9e42f827cb2196cb2a70b6b649f7432a53757a01be"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "196bf071bb0d93b490974b22cc3d22cf27fd02a9"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "d1703f252c25509921399b6294b777d8f6467b38ce8e7adafc15f50609cd6c57"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "594a4e0bd869e422c62a3ddc69ce78a8ceb13fdb"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "04fce3efda93b22808caec1ae8a7df5ef7a00a9069fd8a8ee98bbdecad69e4f6"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
git-tree-sha1 = "544093f278f09315b922ae01484766de29874767"
os = "freebsd"

    [[soapysdr.download]]
    sha256 = "b729e9e05526df3e8a44e924c035eeb8adda51d0ee401a60adc66ecbe2c9ec5f"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81ced5ee67cedeae94bf0d02b6d62ee3df7fd0c7"
os = "windows"

    [[soapysdr.download]]
    sha256 = "369791bf8d4082307962694ecdb1a6f7ae36679b74bccd9b3cc1a614f2a0b96d"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "490b209741f48b832e1f796df9f3677aa6479fd1"
os = "windows"

    [[soapysdr.download]]
    sha256 = "488e6e4be66c650c7e8446588b57a8fea582aeddede7942bb51c51246a7a9ce0"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+0/soapysdr.v0.8.1.x86_64-w64-mingw32-cxx11.tar.gz"
