[[soapysdr]]
arch = "aarch64"
git-tree-sha1 = "50dee20d73b392ca96e10a2649c9b4f4ecf8b3e2"
os = "macos"

    [[soapysdr.download]]
    sha256 = "9ad30b1f3b7372b495e587ea9ce4fc31e2e642fcef737f274cb4142a2a6af26e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.aarch64-apple-darwin.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9f99afb868d837b0ec0660f7516796abfb4c5c0"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "7f7b7849b0e71b8d2e793c840e362630b2586ac2a0a73b2ab16d7f3f1ec5b14d"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.aarch64-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d93e6052af2dae2d3fc1dc8ffb4b69293fb73fe"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "ed20bdee4c6c0797d094e1023fe95da2cd71d349aac70d7d54b036777b282f24"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd13b6bc4ee140e224999762b28bb20516f5fc76"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "0e8c98273a29099bd52b8a423379b27de1099f96fd4f6fcb75047af664ce701f"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.aarch64-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad4ad95bcf9ef4bcdc9d968d10361d264067fe2a"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "3f918e0d1c7b8c31fdd8276befe6288a601abb1ad787ea499ff5400f4ca7cf5f"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d867a18868a43c1ca0a3cefce2f47ba68b43ae94"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "69b2db7868083eb38291fb493b3f58a8cf4feefed5d3e0495378a7451ad49569"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "778cc84ec0e0fe58a219dd15cb9a2db40ea12505"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "50a12609edc567d113003cfd4d54b04b83b27858b4a508e1859bc945dfb268af"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cba8d38ab8d729ea77df39afb5043c314be7c5be"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "c096506894d67002984528acf90d9d8dfa2f381236acbe65ec411eacdf3c0ca2"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43d94f807201f86908527289e1c4d41e49b9ca94"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "6bc826f5e9dff1d70c66e161ee9dca33e09ec67c358c19c32fa98b1993e75af0"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f3e89d21b65c5b76d508456747f752c9cf11252"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "0f0d05de7ac98ee0241d72e00fd693f55369e21ca2e51410faca5d49c863c8d2"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e5631280e65b0d5afef92a40702dffd02a02677"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "420b33868134ac47cdc3ae6b8282fefc2c2b605b661dc477330f5e3eb98b4baa"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f626fd0bbf47b7b47231a326b641fe8d8f4d2220"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "953b29f8712c68c61141df58f5c84cebb0c5e2ec24c7b64dc6cf9fabd900cb49"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71dbea5c173e1409c35b686af4f319a067031f7e"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "8c687fe100b274a77fb4dca1c1ac08216f45058e767951358db829135768b428"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf4b51f2ecbabaf3839d496589cc54c3e93f945f"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "8dee9b55d3b7bafa2ab3bf962ad0004a1174b6fcdb2d9b3bb3c47c56fa8a3a46"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.i686-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "571b17e04a19702f3ffe6b597a86cdf57372dcaa"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "52b238833783579ff901f9d2f58289af6c620bd4be8f9a2989fdfeebfb27e82e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.i686-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e85718f2e34e340f66a5ef7498b03d503f451c2a"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "06be0cc94e7b8b28aacceee22957c6f96e76cd695f212118795adf245ec6f68d"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.i686-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "136399b3e7c9e5d1898be3f36d38a8d3d7e593bf"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "27d716014c9bf1592a6bd6138243d30a9398142b2e9409ea8edbb4d3aa75f5d5"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.i686-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2c4a92db21e3373d14f888e146b37332bbda22d"
os = "windows"

    [[soapysdr.download]]
    sha256 = "54ad08e811dccc4d8751a6609a027a71c07d0330d68707fc827c63507ce599f1"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.i686-w64-mingw32-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d397589ba3058558b162be1073977a01979ef7b7"
os = "windows"

    [[soapysdr.download]]
    sha256 = "c805bd5fb5449b4601d75bfec8d5b34f8ab8bcfbbb7978463ac21cc6fca86694"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.i686-w64-mingw32-cxx11.tar.gz"
[[soapysdr]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36b3c39b8cf5bcad517edbfe67f0c40effea9374"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "df4899b0a996de084b038a9bc138bb77b96470bd45d38e2e38b6e8b7ad052c5e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8afebe8a76a61f2f66fd3cdeb0f972f64ad40ff4"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "118588c5fd96022252d2329356e507016752d95a65cca23e653551e0ce85e90c"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
git-tree-sha1 = "729ea9f5259ca222c6a565e76eb0f2889d16c736"
os = "macos"

    [[soapysdr.download]]
    sha256 = "e9f120064ff4293f52a1ca12e701c10a8aca69b9e2d01d0970c30f4d0d6b9c3b"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-apple-darwin.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec32837fa865da77d0dcdf2a49608c65f8b5751e"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "9c3af0973c9e714dace71a58ec1f6ef73667136d7929f4a11a178fa51128f300"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d2dbc345cb226268e1c465570552bb06727888c"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "c95348529239f494a930241f2021fa858658b626ca470e565e998fc275c7ab84"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8fa7145bd7e0ca304e81f401b5cf2816ff2540f"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "7d7bbabace3140406784dece477986986875bfc283041b2804c5a81ba8f1175e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b0e5deb0e3c42359b9f9c4432936dd69c5fc293"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "dfb5e872f62e13bb94dfcb326716852678bf99a5320b812f127120b2c90e831e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
git-tree-sha1 = "3e3b566b1e67aa517b2080c82df4f960a4678eb3"
os = "freebsd"

    [[soapysdr.download]]
    sha256 = "bb72b2d47dcbf520acbaa0e5f9e4cf4ad806635d2d50672fc435fd1ce7e4696d"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9374d3d888fe5f52d58692fed704f27f4323b23b"
os = "windows"

    [[soapysdr.download]]
    sha256 = "a19185174ac84fd3c186e5af2d21512abd86598a7f1dade68944a1dc78a98145"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6556cc0c813d784a81d71e1783baa8b19962f56"
os = "windows"

    [[soapysdr.download]]
    sha256 = "3c6e0090354b1deb02d2e63b954820d950319a62ecba766116ecf8c1e5264909"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.0+0/soapysdr.v0.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
