[[soapysdr]]
arch = "aarch64"
git-tree-sha1 = "e062e67b93de245f4af86f3246663a9017ecec19"
os = "macos"

    [[soapysdr.download]]
    sha256 = "5a1f55491171cca23392c6f954ac7106954a3a8cfa70e8b6e4fdd83ff4f73f77"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.aarch64-apple-darwin.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d927a0ef4fc39ad23e2d1938e0d021d2b2d9111"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "f865332e5e7cd75802cc111d0ccba5e128ebc7a156da45a3d4654645afc8abfc"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.aarch64-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd11ec109852c166eaa8a2f0363964b59bd3767b"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "2794c0ccb0b0affa421e7194bf044e3fc34f261c8759a1175798cd3dbc0c2788"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.aarch64-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "738322a0c59a71d69b2eaaaf0d2e1087ec80147c"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "a813d6bdbcdbca33dc1d17ba2e1b58887cbe862122432dc11ea04718fed4cf30"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.aarch64-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9af340d16c06383a91ec1c9d5fcc5f206eff0ac4"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "4f48b7ab18d9d6febcea6217f377493fc336b319c3c23616a07a9dd24ebaf9b5"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.aarch64-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "aarch64"
git-tree-sha1 = "3ff02252ddf3ffe2db1d349eee04d25c49324565"
os = "freebsd"

    [[soapysdr.download]]
    sha256 = "272ea00370985c37e2e5cb81b66518ffede3a8a0406a7cb5aad92218e6ca60c8"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.aarch64-unknown-freebsd.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a51e8a6e37754fffee185c036057f8e55bdae0e"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "68996f00eff8f8725a178756023e3acd2f1196cc3d32df4df7d7812fde8bb685"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e7135e8f8bc3753355afb910e3b5218222299f8"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "df5ea87a47e829a899220fe315d6ff705d6c8383725037a9fe2cfc405d4f94c8"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ba575d8af543bd55bb65d8771ca963a6e29dee3"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "3f7324db0db5b248d4f65a93bfe0df4830ca1289d756342bd3d3ad3809c3c093"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cd4590a4ee814b035ca953d44365b30ea554b4a"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "c3639415f084410eda427d9a1d9769d63a456c4e8a3fc3d911fbdd8fb1175d07"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4eb8be0b8b9518b1cc0bc8c3ff24384f53aecbd"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "6a95b133122c97c65453bc47c973245611a1e73721a3222d0b4260b264542f9a"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1ce48e2fdb7adbf341880b42661444a0964ce94"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "9ea59532fa4d45080e6d8dcbce4a8d16b7defbb546ffe28a1964681b77d5072e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bf09461cc000689649f8805aec0b666ee5b95da"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "09cd900a2217663b40c73ca798f7cf652fbb7bc472e3ed5a8018dd6f24a5626a"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[soapysdr]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa4fb4c8259dd42f96fd5fc7d69900ba2940ffdf"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "2ebdab85e04d6bb0c455fc92492d204febe3ac553ded38b7de82fd69fd30fb48"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0ffaea890971639cdb7f29515fff11be28077c4"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "913b4307f3368e8d1d9babb2f1cc60ff93970bc87ce6f5fc1cf4cdea7edb4674"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.i686-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae9159bc8991fc87fe707e5391a7fc055e2e7b33"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "60cf870d05d8b12fbc836e8aa630f9e52ec0e7c1e4749236b76a843982f44449"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.i686-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4d50e3cd44fe09d96ffeaf99e6097ed99cdf849"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "2390cc34deb3b1fd7a6278a0695584b46bb78eab8ba68e22fb4907a1cab69661"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.i686-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec616fd5c2d975d72cd3b649e98b342315d44b29"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "0582fb238e8178124b27e16da6b7ac0a8881ea86f086d96e6542e4c226daae28"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.i686-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88f411270ee0e9ba2f35399a08af71f21dbd7985"
os = "windows"

    [[soapysdr.download]]
    sha256 = "65c60efb8928b215a10b0dbc4498bf4215fe7ec2cd7d38e7a820dd7695d84fde"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.i686-w64-mingw32-cxx03.tar.gz"
[[soapysdr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33815b7b1c144e03e3bd15090c041fd97be159b5"
os = "windows"

    [[soapysdr.download]]
    sha256 = "8ccff20151317ab503217062097ab2d6a025a4dd719293501876a614d5808724"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.i686-w64-mingw32-cxx11.tar.gz"
[[soapysdr]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c07a87265a5c2972b3ece3a676a16f970066c588"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "0b6da475793329d5942b85e5a4a75aaa1798ee8d7d1d2f4f1f6b529f7136f77a"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4a819d8ce98561c6097cffac3bce9903e2ae76e"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "d579e07e06f3ed51639f3840b31eb369c016562fbcc8b899f9634c02578e835d"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b5b3a11fc20ec73fe9943c9e9f42c81b515685e"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "e0f32512892f6c62271a349ada6da6513b8b4f19efb987554ed6193534a4b8ae"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.riscv64-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7c28c6197ce6faa4a0ea528a663baab94357711"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "7d5c02b4f1bf6068654c4f5bbb71a0633cb73e4a3fa76e666bb16489bcf3348e"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.riscv64-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
git-tree-sha1 = "7d8ba5a1c8fcebd3adbc40e417cd480c75f50ef9"
os = "macos"

    [[soapysdr.download]]
    sha256 = "8530985d081301fb84088a9fdc83bbced781bdaf1ae9717b275b970c2c89c6ee"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-apple-darwin.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab3d442a13d92efa247e992da990aa7620e777ae"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "c4948684df88354d68552410213269c1429aecbe47c79dc70774b4db488ce293"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-linux-gnu-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b904cfb58f028b89a25cd13490b275a6f705d3ea"
libc = "glibc"
os = "linux"

    [[soapysdr.download]]
    sha256 = "a46231799b49693fab09564e74dc3aa54919e5c8065302a828707c3aa9663712"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "543f6efb79a485116704a9d49fd7bcd35ec30d60"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "1b678494b4f0cbae0843c31b64d0ae389a48e89008e90cfb1778d5a672b9fa3d"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-linux-musl-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "151a3c019f5b7451f3ce34dc129e7db6c65745c6"
libc = "musl"
os = "linux"

    [[soapysdr.download]]
    sha256 = "e2309bb9a3b6c9f6093651cbb2ddd51dd62c479c5364bfbb182abc12bbed147c"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-linux-musl-cxx11.tar.gz"
[[soapysdr]]
arch = "x86_64"
git-tree-sha1 = "c4e80bdfd5c683a41e0d67fd5cd2b3ab55ddc3e3"
os = "freebsd"

    [[soapysdr.download]]
    sha256 = "a05e5c301bed4c7f3ea12cf8dac9a764ec3167b84eddad279458dc45abc9a901"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d5e1f34ad8aa8ff795368828bbb0dd242698c4b"
os = "windows"

    [[soapysdr.download]]
    sha256 = "0be31998f273edbf7e6c8c52bb30222c9e90e9bbe7a0f819cb12e539ef99db73"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[soapysdr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1663bf36d2923c89a222864adb3ba47e988a03dd"
os = "windows"

    [[soapysdr.download]]
    sha256 = "fd85d3c2aa79a01e4dd7ffb8b7fec27a5a2d888586346d69db98cbf58257e78b"
    url = "https://github.com/JuliaBinaryWrappers/soapysdr_jll.jl/releases/download/soapysdr-v0.8.1+1/soapysdr.v0.8.1.x86_64-w64-mingw32-cxx11.tar.gz"
